### ISSUE TITLE
Добавить линки на локейшн карточку

### ISSUE THREAD

**Issue by olegnazarov23** [nomelnomel/kingsford#1]
![image](https://user-images.githubusercontent.com/8569046/120205221-b3a5c300-c1f7-11eb-9f59-d357c6b9af1e.png)

Телефон будет формат tel:123456789 (click to call)
Адрес - простой линк, он будет идти на google maps локацию

**Comment by nomelnomel** [comment]
done
[https://github.com/nomelnomel/restotest/commit/016c8b4ad9fc6a441b4f53f606f3965050009a49](url)
