### ISSUE TITLE
Заанимировать переходы по табам в меню

### ISSUE THREAD

**Issue by olegnazarov23** [nomelnomel/kingsford#2]
![image](https://user-images.githubusercontent.com/8569046/120205432-f36caa80-c1f7-11eb-899a-db1b0d55e2e6.png)
Можно обычный фейд ин фейд аут, что нибудь просто и со вкусом

Как идея - https://www.csscodelab.com/vue-tabs-transition-animation/

**Comment by nomelnomel** [comment]
так анимация есть, но нужно фиксить размер заливки для разных разрешений

**Comment by nomelnomel** [comment]
после того как Андрей написал, чтобы я переделал на ширину "слова". то адаптировать почти не пришлось
