### ISSUE TITLE
Ховер эффекты на линки

### ISSUE THREAD

**Issue by olegnazarov23** [nomelnomel/kingsford#3]
![image](https://user-images.githubusercontent.com/8569046/120205716-48102580-c1f8-11eb-8188-d38e5afb8fd1.png)

Так как у нас дефолтный стейт уже с подчеркиванием, предлагаю убирать подчеркивание на ховере - примерно вот так https://www.thevillagedallas.com/experience

**Comment by olegnazarov23** [comment]
@nomelnomel тоже самое тут - 
![image](https://user-images.githubusercontent.com/8569046/120205912-84dc1c80-c1f8-11eb-9012-f043d6aaff11.png)

**Comment by nomelnomel** [comment]
done
[https://github.com/nomelnomel/restotest/commit/b190113edee5d46362d17d9fb762323e9e1a4947](url)

**Comment by olegnazarov23** [comment]
@nomelnomel пропустил некоторые - 

<img width="266" alt="Screen Shot 2021-06-01 at 9 21 05 AM" src="https://user-images.githubusercontent.com/8569046/120330557-ec5aa080-c2ba-11eb-91f2-7f098265ae06.png">

То есть любые линки чтобы ховер был

Также можем ховер сменить с того что щас на убирание линии справа влево, как тут - https://cssanimation.rocks/animating-links/

<img width="1119" alt="Screen Shot 2021-06-01 at 9 24 53 AM" src="https://user-images.githubusercontent.com/8569046/120330914-45c2cf80-c2bb-11eb-8cab-b9564a7e472a.png">

только справа влево чтобы шло

**Comment by nomelnomel** [comment]
поменял эффект ховера, навесил на всё, что с андерлайном, а что делать с тем, что без андерлайна, но является линком (телефон на странице location, линки в футере, телефон/мейл/файл на странице catering) 
я пока добавил появление линии в футер, можешь глянуть?

[https://60b66380217ef800084d6001--zen-goldberg-4114ad.netlify.app](url)

**Comment by olegnazarov23** [comment]
я думаю давай пока оставим как ты сделал, если что потом шлифанем
