### ISSUE TITLE
Анимации переходов по страницам

### ISSUE THREAD

**Issue by olegnazarov23** [nomelnomel/kingsford#4]
сделать переходы по страницам анмацию роутов, шторка вылазит снизу вверх как на вилледж далласе только их красным кфг цветом

https://www.thevillagedallas.com/experience как тут только цвет красный

больше инфы по тому как это делается (все встроено в наксте) - https://nuxtjs.org/docs/2.x/features/transitions/

**Comment by nomelnomel** [comment]
@olegnazarov23 пока не получилось как на вилледж, добавил немного другую анимацию (пока учусь Т_Т)
https://60b5f08c5e206900077f8d07--zen-goldberg-4114ad.netlify.app

**Comment by olegnazarov23** [comment]
@nomelnomel ты вцелом отсюда можешь идею взять - https://nuxtjs.org/examples/transitions/
<img width="931" alt="Screen Shot 2021-06-01 at 8 46 39 AM" src="https://user-images.githubusercontent.com/8569046/120325780-fe861000-c2b5-11eb-82c6-06657b07c91e.png">

Также имей в виду что вся анимация должна быть короткая может 0.2с-0.3с

**Comment by nomelnomel** [comment]
Пока поставил прямо как в примере, всё равно как-то не плавно это происходит
[https://60b66380217ef800084d6001--zen-goldberg-4114ad.netlify.app](url)

**Comment by olegnazarov23** [comment]
мне нравится
