### ISSUE TITLE
Убрать layout shift

### ISSUE THREAD

**Issue by olegnazarov23** [nomelnomel/kingsford#5]
Это если не найдешь скажи но суть в том что когда грузишь сайт можно видеть что он дергается (сам лейаут)

Это происходит из за этого - cumulative layout shift. У меня подозрение что это из за слайдера потому что на других страницах он тоже есть, но гораздо меньше - https://60b4d4628a56260007221137--zen-goldberg-4114ad.netlify.app/menu тут 0.1 к примеру.

В идеале должно быть 0

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2F60b4d4628a56260007221137--zen-goldberg-4114ad.netlify.app%2F
<img width="839" alt="Screen Shot 2021-05-31 at 10 31 08 AM" src="https://user-images.githubusercontent.com/8569046/120208515-907d1280-c1fb-11eb-9c20-afce1f060ea5.png">

**Comment by olegnazarov23** [comment]
https://user-images.githubusercontent.com/8569046/120328259-a69cd880-c2b8-11eb-8f70-1d48b124dadb.mov

**Comment by nomelnomel** [comment]
хм, у меня что-то такого не наблюдается о_О

**Comment by nomelnomel** [comment]
@olegnazarov23 
добавил загрузку картинок для галереи с вп, с подключением лэйзилоадинга, на телефонах шифт почти исчез
![image](https://user-images.githubusercontent.com/42649641/121667736-43c6f080-cab3-11eb-8f36-6ff192581c18.png)
